name: dart_image
author: Brendan Duncan <brendanduncan@gmail.com>
version: 1.0.3
homepage: http://bitbucket.org/brendan_duncan/dart_image
description: The image library aims to provide server-side programs the ability to load, manipulate, and save various image file formats.
dependencies:
  benchmark_harness: "^1.0.5"
environment:
  sdk: "^2.0.0"
